# Generated by Django 5.1.4 on 2025-02-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LottoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_number", models.IntegerField(unique=True)),
                ("num_1", models.IntegerField()),
                ("num_2", models.IntegerField()),
                ("num_3", models.IntegerField()),
                ("num_4", models.IntegerField()),
                ("num_5", models.IntegerField()),
                ("num_6", models.IntegerField()),
                ("bonus_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_number", models.IntegerField()),
                ("recommended_numbers", models.JSONField()),
                ("match_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
